# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 20:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.RemoveField(
            model_name='counties',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='counties',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='cty_code',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='dis',
        ),
        migrations.AddField(
            model_name='counties',
            name='const_code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='constituen',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='county_cod',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='county_nam',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='id_field',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='objectid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='shape_leng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
