# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 22:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20190320_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('county_nam', models.CharField(max_length=80)),
                ('const_code', models.FloatField()),
                ('constituen', models.CharField(max_length=80)),
                ('county_ass', models.FloatField()),
                ('county_a_1', models.CharField(max_length=80)),
                ('regist_cen', models.FloatField()),
                ('registrati', models.CharField(max_length=80)),
                ('county_cod', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
            },
        ),
    ]
